### ISSUE TITLE
[protobuf] Failing installing Xbot2 with ros-noetic

### ISSUE THREAD

**Issue by eliapellegrino** [ADVRHumanoids/forest#44]
Setup:

- Linux kernel 5.14.0-1029-oem
- Ubuntu Focal (20.04.3 LTS)
- Ros noetic

After launching
`forest grow --clean xbot2`
in a forest workspace (that was **working**) and try to reinstall it using
`forest grow xbot2`, what I obtained is a conflict between different version of protobuf installed. In particular:

- noetic needs libprotobuf 3.6.1 that is correctly installed (during the installation of ros noetic)
- Ecat master needs libprotobuf 3.0.0 that is correctly installed throgh forest.

The error is this one (just put some lines):
![Screenshot from 2022-03-25 15-45-52](https://user-images.githubusercontent.com/68896265/160143939-2f26cbb5-70c6-4b82-a6b1-3138e040d2d4.png)
Going inside the CMakeLists.txt where this is built (<forest_ws>/src/xbot2/gazebo/CMakeLists.txt"), I notice this strange behavior: 
![Screenshot from 2022-03-25 15-52-04](https://user-images.githubusercontent.com/68896265/160144802-577050cc-8df9-470e-85cd-06cde4834277.png)
gazebo is linking to the protobuf of forest (v 3.0.0) and not the one needed (v3.6.1).
I have try debugging but I didn't manage to solve the issue. Inside gazebo-config.cmake (the one "called" when we call find_package(gazebo) ), we have this line of code:
![Screenshot from 2022-03-25 15-58-16](https://user-images.githubusercontent.com/68896265/160145878-85d26fee-a8e5-4a67-afe6-9244e54e2863.png)
that should make CMake looking for protobuf using Module mode before confi mode (according to [documentation](https://cmake.org/cmake/help/v3.16/command/find_package.html#search-procedure) ), thus bringing cmake towards the FindProtobuf.cmake located at /usr/share/...:
![Screenshot from 2022-03-25 16-10-45](https://user-images.githubusercontent.com/68896265/160148075-38aaad4a-4f6c-4da8-878c-9c9705744d5d.png)
This seems to not be happening.
I notice the same behavior also on my personal laptop (with Linux Kernel 5.4.124 (or something like this), Ubuntu 20.04 and noetic).

Any clue on this?

**Comment by MarcoRuzzon** [comment]
This is indeed a strange behaviour, I assume that the only possible explanation is that FindProtobuf.cmake finds the protobuf inside the forest workspace instead of the one installed at system level.

Nevertheless, I'd say this is not a forest bug but the result of two different packages depending on different versions of the same package, since gazebo does not specify the version in the `find_package(Protobuf REQUIRED)`.

A quick fix for this bug would be to create two different forest workspace: 
-  one with protobuf [3.0.0](https://github.com/ADVRHumanoids/protobuf/tree/xbot2) and ecat_master
- one with protobuf [3.6.1](https://github.com/ADVRHumanoids/protobuf/tree/xbot2_v3.6.x) and xbot2

Unfortunately for this to be successful gazebo-config.cmake needs to be changed:
`find_package(Protobuf REQUIRED)` --> `find_package(Protobuf 3.6.1 CONFIG REQUIRED)`
